"""Infrastructure persistence layer."""

from .database import Database
from .models import (
    AlbumModel,
    ArtistModel,
    ArtistWatchlistModel,
    AutomationRuleModel,
    Base,
    DeezerSessionModel,
    DownloadModel,
    FilterRuleModel,
    PlaylistModel,
    PlaylistTrackModel,
    QualityUpgradeCandidateModel,
    TrackModel,
)
from .repositories import (
    AlbumRepository,
    ArtistRepository,
    ArtistWatchlistRepository,
    AutomationRuleRepository,
    DeezerSessionRepository,
    DownloadRepository,
    FilterRuleRepository,
    PlaylistRepository,
    QualityUpgradeCandidateRepository,
    TrackRepository,
)

__all__ = [
    "Database",
    "Base",
    "ArtistModel",
    "AlbumModel",
    "TrackModel",
    "PlaylistModel",
    "PlaylistTrackModel",
    "DownloadModel",
    "ArtistWatchlistModel",
    "FilterRuleModel",
    "AutomationRuleModel",
    "QualityUpgradeCandidateModel",
    "DeezerSessionModel",
    "ArtistRepository",
    "AlbumRepository",
    "TrackRepository",
    "PlaylistRepository",
    "DownloadRepository",
    "DeezerSessionRepository",
    "ArtistWatchlistRepository",
    "FilterRuleRepository",
    "AutomationRuleRepository",
    "QualityUpgradeCandidateRepository",
]
